### ISSUE TITLE
End-to-End training fails

### ISSUE THREAD

**Issue by mtee** [cvlab-dresden/DSAC#12]
I can do the component-training fine, but when I start the end-to-end training afterwards the program crashes in this line:

https://github.com/cvlab-dresden/DSAC/blob/master/core/cnn.h#L474

The error message is 

> OpenCV Error: Assertion failed (type == B.type()) in gemm, file /home/mikhail/proglibs/opencv/modules/core/src/matmul.cpp, line 1558

I debugged this line and found out that the rotation matrix has the type CV_32F, while two others have type CV_64F. If i naively convert the matrix type in the line above, the programm crashes somewhere else and I am not ready to dive into this rabbit hole yet. 
If I log the type of the hyps[h] here:

https://github.com/cvlab-dresden/DSAC/blob/master/core/cnn.h#L661

it is always 5, i.e. CV_32F.

**Comment by mtee** [comment]
So from the first glance, the issue can be fixed by explicitly converting the rotation matrix coming out of cv::solvePnp [here](https://github.com/cvlab-dresden/DSAC/blob/master/core/cnn.h#L72): 

    rot.convertTo(rot, CV_64F);
    trans.convertTo(trans, CV_64F);

**Comment by ebrach** [comment]
Thanks for bringing this up. I never had this problem, but I can absolutely believe that the matrix types might be inconsistent at some point as I'm rather sloppy in this regard.

Which OpenCV version do you use? At the moment my best guess is that OpenCV changed the handling of type inconsistencies at some point.

**Comment by mtee** [comment]
I am on the OpenCV 3.3. I also think that this is the correct explanation. Well, at least now a solution is documented, in case anybody else will face the same problem

**Comment by ebrach** [comment]
Thanks, yes. Your fix should also be backwards compatible to OpenCV 2.4 (which I used at the time of writing this code). I will probably add your fix to the repository when I have time to test it for OpenCV 2.4.

**Comment by ebrach** [comment]
tdlr: the fix mentioned above will likely break end-to-end training

A quick warning: I upgraded to OpenCV 3.4 and encountered the same problem. While your fix prevents the crash, the underlying problem still remains I think. 

As far as I understand at the moment, it's not a matter of matrix type handling, but the behavior of cv::solvePnP itself. It seems that the current implementation produces weird results when uninitialized matrices are passed as rotation and translation parameters. This was no problem in OpenCV 2.4.

Your fix masks the problem, but the gradients of the scoring function in end-to-end training will be data garbage. I have not tested the following thoroughly yet, but this seems to work for me:

At the beginning of safeSolvePnP in cnn.h  add:
if(rot.type() == 0) rot = cv::Mat_<double>::zeros(1, 3);

**Comment by ebrach** [comment]
I added the type check to cnn.h. Things should now work with OpenCV 3.x
