### ISSUE TITLE
Where is sensorTrans.dat from?

### ISSUE THREAD

**Issue by t-fi** [cvlab-dresden/DSAC#13]
I am interested how you obtained the data for sensorTrans.dat.

The original [microsoft 7Scenes description](https://www.microsoft.com/en-us/research/project/rgb-d-dataset-7-scenes/) does not contain this information. They only mention principal point and focal length of the kinect. 

Background is, mapping the depth image to the rgb image with your method is a little inaccurate with the method used in this repo. Still much better than the raw data of course :)

**Comment by ebrach** [comment]
Hi,
this file contains the estimated relative transformation between RGB camera and depth sensor. I obtained it by manually clicking some correspondences between depth and RGB on a few 7Scenes training images. It can be improved for sure (and you are welcome to provide a better one ;) ) but I found it sufficient for my needs. Inaccuracies could also stem from other calibration parameters that I had to guess based on the sensor that was presumably used. So, in summary: Much room for improvement.

**Comment by t-fi** [comment]
Thats a reasonable approach, I guess I would have wound up doing something similar. Improving the transformation requires some work tho... Do you by chance know any "calibrated" datasets where this work has already been done, ideally by the datasets' creators? I guess such a calibration is inevitable if any kind of physical depth sensor is used, while visual odometry does not have this problem at all.  

And thanks for the quick response!

**Comment by ebrach** [comment]
I'm aware of the 12Scenes dataset by Valentin et al. (http://graphics.stanford.edu/projects/reloc/). However, it is quite easy, with current RGB-only methods scoring 95-99% localization accuracy.

**Comment by t-fi** [comment]
That's exactly what I need, thanks a lot! 3D-Data contains a lot more information and can improve performance tremendously, as shown in Tab. 3 of your 'Less is more' paper :)

**Comment by ebrach** [comment]
Glad to help!
