### ISSUE TITLE
maxloss

### ISSUE THREAD

**Issue by Mona77** [cvlab-dresden/DSAC#15]
Why would you need to divide translation distance by 10:

```
std::min(std::max(rotErr, tErr / 10), MAXLOSS);
```
https://github.com/cvlab-dresden/DSAC/blob/da63cd79a4e4847c45d6f07407bb1ad4027ce26f/core/maxloss.h#L78

**Comment by ebrach** [comment]
Hi,
the parametrization of the pose translation is in Millimeters. Dividing by 10 transforms the error to Centimeters which is more comparable to the rotation error in degrees. Or in other words: It is a custom weighting factor to balance rotation and translation error.
Kind regards,
Eric
