### ISSUE TITLE
How to train on the complete 7-scenes dataset?

### ISSUE THREAD

**Issue by jkznst** [cvlab-dresden/DSAC#4]
Hello Eric, I run your code on each scene (in the 7-scenes dataset) and get similar results as in your paper. But when I train and test on the complete 7-scenes dataset( 260,000 images for training, 170,000 for testing), the performance doesn't match. I subtract the translation (in "translation.txt") from the ground truth pose matrices manually for each scene and comment out the corresponding codes in "read_data.cpp". The training settings are not changed. Could you tell me how to achieve your performance on the complete 7-scenes dataset? Looking forward to your reply.

zhang xin

**Comment by ebrach** [comment]
Hey Xin, 

This is a misunderstanding, thanks for bringing it up! The number "Complete" in the paper does not point to a separate experiment but is just another way to calculate the average performance. "Complete" means that you weight the performance of each scene with the number of test frames it has. Or to put it differently: You consider the 7-Scenes data set as one set of images, but still train individual CNNs for each scene and select the right one depending on the test image.

The experiment you propose (train one pipeline for all images mixed) is also interesting, but the individual scenes do not live in a common coordinate space - i.e. they will be overlapping. The Scene Coordinate CNN will have a hard time to disentangle this (I guess, I didn't try ;) ).

We did something similar to what you propose in our CVPR 16 paper (http://wwwpub.zih.tu-dresden.de/~cvweb/publications/papers/2016/rgbpose.pdf), Section 4.3, last paragraph. But there the approach was to learn to identify the scene and jointly regress scene coordinates using a joint classification regression random forest.

Kind regards,
Eric

**Comment by zhangxinby** [comment]
Thanks for your explanation!

**Comment by jkznst** [comment]
Thanks for your explanation!
