### ISSUE TITLE
interested in trying this with my own image sequences.

### ISSUE THREAD

**Issue by rnunziata** [cvlab-dresden/DSAC#8]
interested in trying this with my own image sequences. Want to integrate with ROS  for visualization driving it using a video or ros bag file. Have you considered opening the interface to allow for this.

**Comment by ebrach** [comment]
No, but I guess adapting our code should be easy, since it is OpenCV-based. Just have a look to test_ransac. The jp::img_bgr_t that is used as the input image is just an typedef for a standard RGB cv::Mat. Loading Videos via OpenCV should be super easy - not sure about ROS.

**Comment by rnunziata** [comment]
Yes...that works....

What is the function of translation.txt file.
 I am testing with a video for a office very similar in appearance to the image seq in your test folder.  
The  translation.txt in your test data is as follows:
-0.727424987205 -0.964973996389 1.87781801284

Is this the  center , is it in normalized to Rodrigues?
How would I set the file for my test data?

Thank you for help.

**Comment by ebrach** [comment]
You can find information about the translation.txt in the documentation.pdf:

"The file translation.txt contains a normalization
translation applied to all poses of the data set. We found that the EPnP implementation
of OpenCV is sensitive to translation. We translated each scene,
such that its bounding box is centered at (0, 0, 0). This translation is different
for each scene. This file is optional."

I do not understand the second part of your question.
